### PR TITLE
Use key encoder/decoders for IRIs.

### PR DESCRIPTION
**Pull request by balhoff**
Added KeyDecoder/KeyEncoder for IRIs, so that we don't convert to strings before the response is rendered.

### CODE REVIEW

**Comment by jdr0887** [comment]
With these changes, the simpleQueryTest fails.  Here is the message on the server:

io.circe.DecodingFailure$$anon$2: BiolinkClass does not exist: gene: DownField(category),DownField(n0),DownField(nodes),DownField(query_graph),DownField(message)

**Comment by balhoff** [comment]
I think we need to fix the input, right? Should be `biolink:Gene` instead of `biolink:gene`, etc.

**Comment by jdr0887** [comment]
I think the tests need to be CamelCase'd

**Comment by jdr0887** [comment]
Ok, having fixed the test, it runs fine.

**Comment by balhoff** [comment]
Thanks! Do you want to add to this branch? Or make a separate PR?

**Comment by jdr0887** [comment]
I can add to this branch if you make it a draft PR, right?

**Comment by balhoff** [comment]
> I can add to this branch if you make it a draft PR, right?

You should be able to just push to this branch.

**Comment by jdr0887** [comment]
Yep, pushed.

**Review by jdr0887 — APPROVED** [review]

**Pull request merged**
