### PR TITLE
Stop nesting HttpClient layer inside ZIO.

### PR DESCRIPTION
**Pull request by balhoff**
I finally figured out how to collapse `UIO[TaskLayer[HttpClient]]` to `TaskLayer[HttpClient]`...

### CODE REVIEW

**Review by jdr0887 — COMMENTED** [review]
My only issue with this is to assert that the tests still run successfully...in particular, QueryServiceTest.testSimpleQuery

**Comment by balhoff** [comment]
> My only issue with this is to assert that the tests still run successfully...in particular, QueryServiceTest.testSimpleQuery

In theory nothing should change. Would you be willing to test it?

**Comment by jdr0887** [comment]
I ran QueryServiceTest.testSimpleQuery locally and the output looks good to me.

**Review by jdr0887 — APPROVED** [review]

**Comment by balhoff** [comment]
Thanks!

**Pull request merged**
