### PR TITLE
Issue 196

### PR DESCRIPTION
**Pull request by jdr0887**
This is a start on improving the testing for cam-kp-api...addressing #196

### CODE REVIEW

**Comment by jdr0887** [comment]
From the sbt prompt, "test" will run all the unit tests in src/test/scala and "it:test" will run all the tests in src/it/scala.  Before running "it:test", make sure you have see an instance of "renciorg/cam-kp-api" when you run "docker image ls".

**Comment by jdr0887** [comment]
From the sbt prompt, running, "sbt clean coverage test coverageReport" will generate a coverage report in "target/scala-2.13/scoverage-report/".

**Comment by balhoff** [comment]
@jdr0887 I'm getting stuck here running `sbt it:test`:

```
14:57:24 [zio-default-blocking-1] INFO  ?.1] - Container renciorg/cam-kp-api:0.1 is starting: 0e8c5b33b3048511e6155f449945c61077e1e8ec95f275311d9e98ec89468e39 
14:57:24 [zio-default-blocking-1] WARN  o.t.c.w.s.HttpWaitStrategy - Unexpected error occurred - will proceed to try to wait anyway 
java.lang.IllegalStateException: Target port 8080 is not exposed
	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.lambda$waitUntilReady$2(HttpWaitStrategy.java:197)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:197)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:892)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:440)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
	at com.dimafeng.testcontainers.SingleContainer.start(Container.scala:46)
	at org.renci.cam.it.TestContainer$.$anonfun$camkpapi$1(TestContainer.scala:19)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:488)
	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:776)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Any ideas?

**Comment by jdr0887** [comment]
My understanding is that that "java.lang.IllegalStateException: Target port 8080 is not exposed" exception is part of the WaitStrategy.  Meaning that no tests are run until that condition is met and the exception is just a warning.  The test should continue to run despite this warning and when the condition is satisfied.

**Review by balhoff — APPROVED** [review]
🎉

**Pull request merged**
