### PR TITLE
Add prefix overrides component

### PR DESCRIPTION
**Pull request by Shalsh23**

### CODE REVIEW

**Comment by Shalsh23** [comment]
Fixes #199 #211

**Comment by Shalsh23** [comment]
Need to write a test for this PR before marking it ready.

**Review by balhoff — CHANGES_REQUESTED** [review]
Looks good—can you resolve the git conflicts?

**Comment by Shalsh23** [comment]
> Looks good—can you resolve the git conflicts?

Done. I kept the changes made in this branch over master, for pulling biolinkPrefixes. Please let me know though, if that isn't how we want to handle them.

**Comment by balhoff** [comment]
@jdr0887 can you please review, since we had some other recent changes to prefix loading?

**Review by jdr0887 — APPROVED** [review]

**Review by balhoff — APPROVED** [review]

**Pull request merged**
